### ISSUE TITLE
[BUG REPORT] Chipped block recipes throw error in JEI interface

### ISSUE THREAD

**Issue by mmsheeks** [Hilistia/smp#3]
**Describe the bug**
When viewing any recipe that uses one of the Chipped workbenches, the JEI interface throws an exception that is visible to the player.

**To Reproduce**
1. Open your inventory (E)
2. Select the JEI search box and type "@Chipped"
3. Select any of the variant blocks
4. Hover over the red error message, exception is in the tooltip

**Expected behavior**
The recipe should display.

**Screenshots**
![image3](https://github.com/user-attachments/assets/e74bfaeb-16e1-4e45-b979-e546b5eec6a4)
![image2](https://github.com/user-attachments/assets/270d26be-8a73-4297-8b17-b743559a92bd)
![image](https://github.com/user-attachments/assets/c62e08d8-da34-4a48-a68f-3066d132dd82)

**System (please complete the following information):**
 - OS: Windows 11
 - Modpack version: v0.1.1

**Additional context**
Problem originally reported by Zhag, recreated by Zen and Cham. This is likely a version mismatch between Chipped and JEI.

**Comment by Zhagoul** [comment]
Possible fix with EMI Version 1.1.17+
See [this issue here.](https://github.com/emilyploszaj/emi/issues/763)

**Comment by mmsheeks** [comment]
Confirmed fixed in EMI 1.1.18

![image](https://github.com/user-attachments/assets/e9f44813-d63b-4471-8de5-8d562d26d17c)
