### ISSUE TITLE
[BUG] Two recipes for wheat dough

### ISSUE THREAD

**Issue by BenjaminCelis** [Hilistia/smp#31]
## Describe the bug
Both Farmer's Delight and Create have a mixing recipe for wheat dough, which makes mixers behave a bit unexpected.

## To Reproduce
pump water into Basin
Put stack of wheat flour into basin.
Let mix for a bit until a few doughs are made.
Put in more wheat flour

## Expected behavior
Usually when crafting things with mixers, the produced item cannot go higher than it's stack size, because of the two recipes it can.

## System (please update as needed):
 - OS: Windows 11
 - Modpack version v0.1.2

**Comment by mmsheeks** [comment]
reopening pending deploy
