### ISSUE TITLE
[BUG] 2 egg recipes

### ISSUE THREAD

**Issue by BenjaminCelis** [Hilistia/smp#32]
## Is your feature request related to a problem? Please describe.
Fried Egg and Cooked egg can be used to make all the foods, but are made through different ways.

Cooked eggs (Naturalist) is made in furnace, Fried Eggs (Farmer's Delight) is made in the skillet.
JEI recipe for both shows the Furnace Recipe

## Describe the solution you'd like
only make one type craftable

**Comment by mmsheeks** [comment]
reopening pending deploy
