### ISSUE TITLE
[MODS] Vibrant Item Vaults

### ISSUE THREAD

**Issue by BenjaminCelis** [Hilistia/smp#42]
## What is the goal of adding or removing these mods?
Making Item vaults more easily placed in builds, and color coding them.

## What mods are impacted?
https://modrinth.com/mod/create-vibrant-vaults

**Additional context**
I suggest removing the shipping containers, since those won't fit the vibes

**Comment by mmsheeks** [comment]
I like this suggestion, and yes we'll want to remove the recipes for the shipping containers. @BenjaminCelis if you want to put together that item ID list for the recipe remover? we can add this in the next release if we've got those tucked away.

**Comment by BenjaminCelis** [comment]
Will do

**Comment by mmsheeks** [comment]
Config is now ready. Will add mod to server and client for v0.2.1 update
