### ISSUE TITLE
[MODS] Decorational Statues

### ISSUE THREAD

**Issue by BenjaminCelis** [Hilistia/smp#48]
## What is the goal of adding or removing these mods?
Addings a fun way to add statues in the world, could also be used to make builds more lively with "npc's"

## What mods are impacted?
https://www.curseforge.com/minecraft/mc-mods/straw-statues

**Additional context**

**Comment by mmsheeks** [comment]
Added Straw Statues from modrinth sourcd: https://modrinth.com/mod/straw-statues/versions?g=1.20.1&l=fabric
