### ISSUE TITLE
[FEAT] Add Seasons Compatability to Spectrum Saplings

### ISSUE THREAD

**Issue by BenjaminCelis** [Hilistia/smp#51]
## Is your feature request related to a problem? Please describe.
Add Seasons Compatability to Spectrum Saplings

## Describe the solution you'd like
Add Seasons Compatability to Spectrum Saplings

## Describe alternatives you've considered
N.A.

**Additional context**
N.A.

**Comment by mmsheeks** [comment]
Config deployed to alpha server
