### ISSUE TITLE
[FEAT] AFK command

### ISSUE THREAD

**Issue by mmsheeks** [Hilistia/smp#57]
## Is your feature request related to a problem? Please describe.
Players need a way to indicate when they're stepping away but remaining logged in.

## Describe the solution you'd like
Find a mod, or introduce this as a first simple feature in the core mod, to add an `/afk` command that alters the player's tab list appearance. The player moving or interacting with an inventory should disable this status.

**Comment by KayQueen** [comment]
Recommend https://modrinth.com/mod/afkplus

**Comment by mmsheeks** [comment]
Added [AfkPlus](https://modrinth.com/mod/afkplus) and [Text Placeholder API](https://modrinth.com/mod/placeholder-api/versions?g=1.20.1&l=fabric)

config changes are staged in PR #63
